// Pushes employee USER RECORDS from Firestore into the Hikvision device, so you
// don't hand-type names/IDs on the keypad. It also (re)writes employee-map.json
// so scans route to the right app account.
//
//   Firestore employees  ──>  device UserInfo (employeeNo + name)
//                        └──>  employee-map.json (deviceNo -> app employeeId)
//
// NOTE: this syncs the user *records* only. The actual fingerprint must still be
// captured once at the device (place finger on the sensor) — biometrics can't be
// pushed over the network. After syncing, on the device just pick the existing
// user and scan their finger; no typing needed.
//
// Run:  npm run sync:users
const path = require("path");
const fs = require("fs");
const admin = require("firebase-admin");
const config = require("./src/config");
const { digestFetch } = require("./src/digest");

const keyPath = path.join(__dirname, "serviceAccountKey.json");
if (!fs.existsSync(keyPath)) {
  console.error("Missing serviceAccountKey.json in hikvision-bridge/.");
  process.exit(1);
}
admin.initializeApp({ credential: admin.credential.cert(require(keyPath)) });
const db = admin.firestore();

// Only people who actually clock in at the device. Managers/admins use the web
// portal, so by default we skip them (set SYNC_ALL_ROLES=true to include them).
const SYNC_ALL = process.env.SYNC_ALL_ROLES === "true";

// Device person IDs are numeric (no dash). Derive one from the app Employee ID
// by keeping its digits, e.g. "EMP-1001" -> "1001".
function deviceNoFor(employeeId) {
  const digits = String(employeeId).replace(/\D/g, "").replace(/^0+/, "");
  return digits || null;
}

async function listExisting() {
  const found = new Map(); // employeeNo -> name
  let pos = 0;
  for (let page = 0; page < 100; page += 1) {
    const res = await digestFetch(
      `${config.deviceBaseUrl}/ISAPI/AccessControl/UserInfo/Search?format=json`,
      {
        method: "POST",
        username: config.username,
        password: config.password,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          UserInfoSearchCond: { searchID: "qui-sync", searchResultPosition: pos, maxResults: 30 },
        }),
      },
    );
    if (!res.ok) throw new Error(`UserInfo/Search HTTP ${res.status}`);
    const json = await res.json();
    const info = json.UserInfoSearch || {};
    const list = Array.isArray(info.UserInfo) ? info.UserInfo : [];
    list.forEach((u) => found.set(String(u.employeeNo), u.name || ""));
    pos += list.length;
    if (list.length === 0 || info.responseStatusStrg === "OK" || info.responseStatusStrg === "NO MATCH") break;
    if (info.totalMatches && pos >= info.totalMatches) break;
  }
  return found;
}

function userPayload(employeeNo, name) {
  return {
    UserInfo: {
      employeeNo,
      name,
      userType: "normal",
      Valid: {
        enable: true,
        beginTime: "2024-01-01T00:00:00",
        endTime: "2037-12-31T23:59:59",
        timeType: "local",
      },
      doorRight: "1",
      RightPlan: [{ doorNo: 1, planTemplateNo: "1" }],
    },
  };
}

async function addUser(employeeNo, name) {
  const res = await digestFetch(`${config.deviceBaseUrl}/ISAPI/AccessControl/UserInfo/Record?format=json`, {
    method: "POST",
    username: config.username,
    password: config.password,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(userPayload(employeeNo, name)),
  });
  const text = await res.text();
  return { ok: res.ok, status: res.status, text };
}

async function modifyUser(employeeNo, name) {
  const res = await digestFetch(`${config.deviceBaseUrl}/ISAPI/AccessControl/UserInfo/Modify?format=json`, {
    method: "PUT",
    username: config.username,
    password: config.password,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(userPayload(employeeNo, name)),
  });
  const text = await res.text();
  return { ok: res.ok, status: res.status, text };
}

(async () => {
  console.log("Syncing employees → Hikvision device user records…\n");
  console.log(`Device: ${config.deviceBaseUrl}\n`);

  const snap = await db.collection("employees").get();
  const existing = await listExisting();

  const map = { _comment: "Auto-generated by sync-users.js. LEFT = device person ID, RIGHT = app Employee ID." };
  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const doc of snap.docs) {
    const d = doc.data();
    const employeeId = doc.id;
    const role = (d.accessRole || "staff").toLowerCase();
    if (!SYNC_ALL && role !== "staff") {
      skipped += 1;
      continue;
    }
    const employeeNo = deviceNoFor(employeeId);
    const name = d.fullName || employeeId;
    if (!employeeNo) {
      console.log(`  ⚠ ${employeeId}: can't derive a numeric device ID — skipped`);
      skipped += 1;
      continue;
    }

    map[employeeNo] = employeeId;

    try {
      if (existing.has(employeeNo)) {
        const r = await modifyUser(employeeNo, name);
        if (r.ok) {
          console.log(`  ✎ updated  #${employeeNo.padEnd(6)} ${name}  → ${employeeId}`);
          updated += 1;
        } else {
          console.log(`  ✗ update  #${employeeNo}: HTTP ${r.status} ${r.text.slice(0, 120)}`);
        }
      } else {
        const r = await addUser(employeeNo, name);
        if (r.ok) {
          console.log(`  ＋ created #${employeeNo.padEnd(6)} ${name}  → ${employeeId}`);
          created += 1;
        } else {
          console.log(`  ✗ create  #${employeeNo}: HTTP ${r.status} ${r.text.slice(0, 120)}`);
        }
      }
    } catch (e) {
      console.log(`  ✗ ${employeeId} (#${employeeNo}): ${e.message}`);
    }
  }

  // Rewrite employee-map.json so the bridge routes scans to the right account.
  const mapPath = path.join(__dirname, "employee-map.json");
  fs.writeFileSync(mapPath, JSON.stringify(map, null, 2));

  console.log(`\nDone. created ${created}, updated ${updated}, skipped ${skipped}.`);
  console.log(`employee-map.json written (${Object.keys(map).length - 1} mappings).`);
  console.log("\nNEXT: on the device, open each user and capture their fingerprint");
  console.log("(User Management → pick the person → add fingerprint). No typing needed.");
  console.log("Then restart the bridge:  npm start");
  process.exit(0);
})().catch((err) => {
  console.error("Sync failed:", err.message || err);
  process.exit(1);
});
